language: php
addons:
  ssh_known_hosts:
  - michels.yawik.org
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.npm"
env:
  global:
  - PECLMONGO="mongodb-stable"
matrix:
  fast_finish: true
  include:
  - php: '7.4'
    env: COVERAGE=no
services:
- mongodb
before_install:
- openssl aes-256-cbc -K $encrypted_587603cc4448_key -iv $encrypted_587603cc4448_iv -in .travis/michels.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
- sudo apt-get update > /dev/null
- if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi;
- pecl channel-update pecl.php.net
- curl -LO https://deployer.org/deployer.phar
- chmod +x deployer.phar
- ssh yawik@michels.yawik.org ls -la
install:
- pecl install -f ${PECLMONGO}
- export HASH=de1d724299780d927cb9ed14268449ac8a28204b;
- phpenv config-add .travis/phpenv.ini
- COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deployer.phar deploy
    on:
      branch: master

before_script:
- if [[ $COVERAGE != yes ]]; then composer run start-selenium --timeout=0 > /dev/null
  2>&1 & sleep 5; composer run serve --timeout=0 > /dev/null 2>&1 & sleep 3; fi
script:
- "ls -la"
after_failure:
- ./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "build/behat/*.log"
- ./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "log/*.log"
- ./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "log/tracy/*.*"
- IMGUR_CLIENT_ID=bec050c54e1bb52 ./vendor/bin/imgur-uploader build/behat/*.png

