<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2020 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

$id = $this->element->getEntity()->getId();
$lang = $this->params('lang');

?>
<h3><?php echo $this->translate("Job details")?></h3>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <iframe id="editJob" style="width:100%; height:800px;" src="<?php
                $job = $this->element->getEntity();
                if ($job instanceOf \Jobs\Entity\JobSnapshot) {
                    $linkOptions = ['query' => ['snapshot' => $job->getSnapshotId()]];
                } else {
                    $linkOptions = [];
                }
                echo $this->url('lang/jobs/editTemplate', array('id' => $id), $linkOptions); ?>"></iframe>
            </div>
        </div>
    </div>
</div>
